version: 0.2
phases: 
  install: 
    commands: 
      - apt-get update -y
      - apt-get install -y maven
  build: 
    commands: 
      - mvn clean package
artifacts:
  files: 
    - target/devops.war
